### ISSUE TITLE
attempt to index a nil value (global 'MP')

### ISSUE THREAD

**Issue by BjornB2** [prestonelam2003/CobaltEssentials#11]
I'm seeing these log entries and I am not getting the CobaltDB folder.

```
 [INFO] Loading plugin : CobaltEssentials-master
 [WARN] CE-RCON.lua \| ...mmp/Resources/Server/CobaltEssentials-master/CE-RCON.lua:15: attempt to index a nil value (global 'MP')
 [WARN] CobaltDB.lua \| ...mp/Resources/Server/CobaltEssentials-master/CobaltDB.lua:19: attempt to index a nil value (global 'MP')
 [WARN] CobaltEssentialsLoader.lua \| ...erver/CobaltEssentials-master/CobaltEssentialsLoader.lua:4: attempt to index a nil value (global 'MP')

```

Running BeamMP in a docker container on a Synology NAS.
Docker container is rouhim/beammp-server 
Only other server mod is Guestmanager.

Is this a bug or something with my server?

**Comment by 20dka** [comment]
Hey there
Cobalt Essentials has been updated in anticipation of the BeamMP server version 3.0 which is currently in early access. It should get released to the public soon

**Comment by BjornB2** [comment]
Is there a Cobalt version that I can use with the current BeamMP server?

**Comment by 20dka** [comment]
No, as the previous (public) BeamMP server is not stable enough to run CE on it. EA testing should only last a few days
